# -*- coding: utf-8 -*-
"""Untitled47.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wZGAYzn2SZYNP8Uazy_TMvP0wD_GLkeV
"""

import numpy as np

def feature_engineering(player_obs):
  # columns = ended?, Card, Dealer, sb, bb, put_contr0, put_contr1, stack0, stack1, put
  cc = len(player_obs["com_card"])
  h = 6 * 2 * player_obs["num_rounds"]
  row = np.zeros((1,10 + cc + h +1))
  total = np.sum(player_obs['initial_stacks'])
  row[0,0] = player_obs["cards"][0]
  row[0,1] = player_obs["dealer"] 
  row[0,2] = player_obs["blinds"][0] / total
  row[0,3] = player_obs["blinds"][1] / total
  row[0,4] = player_obs["put_contr"][0] / total
  row[0,5] = player_obs["put_contr"][1] / total
  row[0,6] = player_obs["stacks"][0] / total
  row[0,7] = player_obs["stacks"][1] / total
  row[0,8] = player_obs["put"] / total
  row[0,9] = player_obs["com_card_shown"]
  row[0,10:10+cc] = player_obs["com_card"]

  row[0, 10+cc:-1] = np.array(player_obs['player_hist']).flatten()
  row[0, -1] = player_obs["cards"][1]
  return row

def feature_engineering_p1(player_obs):
  # columns = ended?, Card, Dealer, sb, bb, put_contr0, put_contr1, stack0, stack1, put
  cc = len(player_obs["com_card"])
  h = 6 * 2 * player_obs["num_rounds"]
  row = np.zeros((1,10 + cc + h + 1))
  total = np.sum(player_obs['initial_stacks'])
  row[0,0] = player_obs["cards"][1]
  row[0,1] = 1 - player_obs["dealer"]
  row[0,2] = player_obs["blinds"][0] / total
  row[0,3] = player_obs["blinds"][1] / total
  row[0,4] = player_obs["put_contr"][1] / total
  row[0,5] = player_obs["put_contr"][0] / total
  row[0,6] = player_obs["stacks"][1] / total
  row[0,7] = player_obs["stacks"][0] / total
  row[0,8] = player_obs["put"] / total
  row[0,9] = player_obs["com_card_shown"]
  row[0,10:10+cc] = player_obs["com_card"]
  
  row[0, 10+cc:-1] = np.array(player_obs['player_hist'])[::-1].flatten()
  row[0, -1] = player_obs["cards"][0]
  return row
  
def fe_dummy(player_obs):
  cc = len(player_obs["com_card"])
  h = 6 * 2 * player_obs["num_rounds"]
  row = np.zeros((1,10 + cc + h+1))
  row[0,0] = player_obs["cards"][0]
  row[0,10:10+cc] = player_obs["com_card"]
  return row
  
def fe_dummy_p1(player_obs):
  cc = len(player_obs["com_card"])
  h = 6 * 2 * player_obs["num_rounds"]
  row = np.zeros((1,10 + cc + h+1))
  row[0,0] = player_obs["cards"][1]
  row[0,10:10+cc] = player_obs["com_card"]
  return row